title: ihD | Global Technology Consultant
email: IHD@ihd-hk.com
description: > # this means to ignore newlines until "baseurl:"
  ihD Ltd is a Hong Kong-registered Private Limited Company, specialising in IT,
  ELV & Security, and Audio-Visual Systems, as well as Mechanical & Architectural
  Acoustics, design and Consultancy. Our company is not involved in any way in the
  supply of equipment nor in installation. We focus instead on Design, Consultancy,
  and Project Management, allowing us to remain independant, specifying equipment
  and systems most suited to our clients technical and budgetary needs.
repository: ihd-hk/ihd-hk.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  parse_block_html: true
  math_engine: mathjax # Forced Default from GH Pages
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - assets/bootstrap
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
permalink: /news/:year-:month-:day--:title:output_ext

excerpt_separator: '<!-- more -->'

twitter:
  card: summary_large_image

# Navigation
navigation:
  en:
  - text: Home
    url: '/'
  - text: About
    url: '/about.html'
  - text: Team
    url: '/team.html'
  - text: Services
    url: '/services.html'
  - text: Projects
    url: '/projects.html'
  - text: Contact
    url: '/contact.html'
  - text: News
    url: '/news.html'
  ch:
  - text: 主页
    url: '/ch/'
  - text: 关于德勤
    url: '/ch/about.html'
  - text: 我们的团队
    url: '/ch/team.html'
  - text: 我们的服务
    url: '/ch/services.html'
  - text: 我们的项目
    url: '/ch/projects.html'
  - text: 联系我们
    url: '/ch/contact.html'
  - text: 新闻
    url: '/ch/news.html'

# Hack to define empty array for Jekyll: https://github.com/jekyll/jekyll/issues/3246#issuecomment-68398379
emptyArray: []

# Hide futures posts - GH shows them!
future: false

# CANNOT CHANGE THESE
lsi: false
safe: true
source: ""
incremental: false
highlighter: rouge
gist:
  noscript: false
# kramdown:
#   math_engine: mathjax
